
openapi: 3.1.0
info:
  title: Teams API Reference
  version: "1.0"
  summary: API
servers:
  - url: "https://app.vessel.dev"
security:
  - VesselAPIToken: []
paths:
  /api/actions/teams/messages/create:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                   id:
                     type: string
                   createdDateTime:
                     type: string
                     format: date-time
                   body:
                     type: object
                     properties:
                       content:
                         type: string
                     required:
                       - content
                   channelIdentity:
                     type: object
                     properties:
                       teamId:
                         type: string
                       channelId:
                         type: string
                     required:
                       - teamId
                       - channelId
              examples:
                example-1:
                  value:
                     id: elit incididunt
                     createdDateTime: '1956-05-16T12:13:57.0Z'
                     body:
                       content: exercitation est laborum irure quis
                     channelIdentity:
                       teamId: enim
                       channelId: dolor sint ea tempor
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                 text:
                   type: string
                 channelId:
                   type: string
                 teamId:
                   type: string
            examples:
              example-1:
                value:
                     text: sunt enim consequat ea dolore
                     channelId: fugiat cupidatat
                     teamId: enim commodo eiusmod laborum in
      operationId: create-message
      parameters:
      - name: x-vessel-access-token
        in: header
        description: Access Token
        required: true
        schema:
          type: string
    parameters: []
  /api/actions/teams/channels/list:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                   value:
                     type: array
                     items:
                       type: object
                       properties:
                         id:
                           type: string
                         displayName:
                           type: string
                         createdDateTime:
                           type: string
                           format: date-time
                       required:
                         - id
                         - displayName
                         - createdDateTime
                   '@odataNextLink':
                     type: string
              examples:
                example-1:
                  value:
                     value:
                       - id: aliquip
                         displayName: in Duis velit pariatur irure
                         createdDateTime: '2012-06-04T02:06:01.0Z'
                         idea_: false
                     '@odataNextLink': laboris Excepteur dolor cillum
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                 teamId:
                   type: string
                 cursor:
                   type: string
            examples:
              example-1:
                value:
                     teamId: sint dolor consequat ex
                     cursor: mollit non cillum
      operationId: list-channels
      parameters:
      - name: x-vessel-access-token
        in: header
        description: Access Token
        required: true
        schema:
          type: string
    parameters: []
  /api/actions/teams/members/list:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                   value:
                     type: array
                     items:
                       type: object
                       properties:
                         id:
                           type: string
                         displayName:
                           type: string
                       required:
                         - id
                         - displayName
                   '@odataNextLink':
                     type: string
              examples:
                example-1:
                  value:
                     value:
                       - id: sit in voluptate velit
                         displayName: magna laboris sint Lorem elit
                     '@odataNextLink': ea reprehenderit laboris Lorem dolore
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                 teamId:
                   type: string
                 cursor:
                   type: string
            examples:
              example-1:
                value:
                     teamId: incididunt Lorem ad ex Ut
                     cursor: aute Duis dolore anim
      operationId: list-members
      parameters:
      - name: x-vessel-access-token
        in: header
        description: Access Token
        required: true
        schema:
          type: string
    parameters: []
  /api/actions/teams/teams/list:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                   value:
                     type: array
                     items:
                       type: object
                       properties:
                         id:
                           type: string
                         displayName:
                           type: string
                       required:
                         - id
                         - displayName
                   '@odataNextLink':
                     type: string
              examples:
                example-1:
                  value:
                     value:
                       - id: in sunt
                         displayName: sunt amet dolore
                     '@odataNextLink': Excepteur non laboris
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                 cursor:
                   type: string
            examples:
              example-1:
                value:
                     cursor: ea commodo irure in
      operationId: list-teams
      parameters:
      - name: x-vessel-access-token
        in: header
        description: Access Token
        required: true
        schema:
          type: string
    parameters: []
  /api/passthrough/teams:
    post:
      summary: Passthrough Request
      operationId: passthrough
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ""
                type: object
                properties:
                  headers:
                    type: object
                  url:
                    type: string
                    description: The full URL that the request was sent to.
                  statusCode:
                    type: number
                    description: The HTTP status code of the response from the downstream system.
                  body:
                    AnyValue:
                      description: The body of the response from the downstream system.
                required:
                  - id
              examples:
                example-1:
                  value:
                    headers:
                      content-type: application/json
                    url: https://sometool.com/api/v1/endpoint
                    statusCode: 200
                    body:
                      id: 123123123123
                      success: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                method:
                  type: string
                  enum:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE
                path:
                  type: string
                  description: "The path to send the request to. Vessel handles the domain, for example, a request to Salesforce would use 'services/data/v52.0/sobjects/Account' instead of 'https://mydomain.my.salesforce.com/services/data/v52.0/sobjects/Account'."
                body:
                  type: object
                  description: "The body of the request."
                query:
                  type: object
                  description: "The query parameters to send with the request as key value pairs. These are appended to the URL when the request is sent to the integration provider."
              required:
                - accessToken
                - method
                - path
            examples:
              example-1:
                value:
                  accessToken: string
                  method: PATCH
                  path: services/data/v53.0/sobjects/Account/0011A00001XQ4ZUQA1
                  body:
                    - Name: "Vessel"
        description: ""
      description: Send an authenticated passthrough request to the downstream system. This is useful for making requests to endpoints that are not yet supported by Vessel.
